version: 2
updates:
  - package-ecosystem: npm
    directory: /src/main/frontend
    schedule:
      interval: weekly
    versioning-strategy: increase
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      xterm:
        patterns:
          - "@xterm/*"
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
