name: Kubernetes Dashboard (SNAPSHOTS)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish-snapshot-image-platform:
    name: Publish YAKD Snapshot (${{ matrix.platform.arch }})
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform: [{arch: amd64, runner: ubuntu-latest}, {arch: arm64, runner: macos-latest-large}]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Package
        run: |
          mvn -Pbuild-frontend clean package
      - name: Docker Hub Login
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build
        run: |
          docker build                                                      \
            --build-arg VERSION=snapshot                                    \
            -f src/main/docker/Dockerfile.build                             \
            --tag marcnuri/yakd:snapshot-${{ matrix.platform.arch }}        \
            --platform linux/${{ matrix.platform.arch }}
            .
      - name: Push
        run: |
          docker push marcnuri/yakd:snapshot-${{ matrix.platform.arch }}
